# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import sys  # 导入sys模块




class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(699, 487)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalFrame = QtWidgets.QFrame(self.centralwidget)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout.addWidget(self.horizontalFrame, 0, 3, 1, 1)
        self.horizontalFrame1 = QtWidgets.QFrame(self.centralwidget)
        self.horizontalFrame1.setObjectName("horizontalFrame1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalFrame1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout.addWidget(self.horizontalFrame1, 0, 4, 1, 1)
        self.openGLWidget_5 = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget_5.setObjectName("openGLWidget_5")
        self.gridLayout.addWidget(self.openGLWidget_5, 3, 3, 1, 1)
        self.openGLWidget_2 = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget_2.setObjectName("openGLWidget_2")
        self.gridLayout.addWidget(self.openGLWidget_2, 1, 1, 1, 1)
        self.openGLWidget_7 = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget_7.setObjectName("openGLWidget_7")
        self.gridLayout.addWidget(self.openGLWidget_7, 3, 4, 1, 1)
        self.openGLWidget_4 = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget_4.setObjectName("openGLWidget_4")
        self.gridLayout.addWidget(self.openGLWidget_4, 3, 1, 1, 1)
        self.openGLWidget_9 = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget_9.setObjectName("openGLWidget_9")
        self.gridLayout.addWidget(self.openGLWidget_9, 1, 4, 1, 1)
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget.setObjectName("openGLWidget")
        self.gridLayout.addWidget(self.openGLWidget, 4, 1, 1, 1)
        self.openGLWidget_3 = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget_3.setObjectName("openGLWidget_3")
        self.gridLayout.addWidget(self.openGLWidget_3, 4, 3, 1, 1)
        self.openGLWidget_6 = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget_6.setObjectName("openGLWidget_6")
        self.gridLayout.addWidget(self.openGLWidget_6, 4, 4, 1, 1)
        self.openGLWidget_8 = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget_8.setObjectName("openGLWidget_8")
        self.gridLayout.addWidget(self.openGLWidget_8, 1, 3, 1, 1)
        self.horizontalFrame2 = QtWidgets.QFrame(self.centralwidget)
        self.horizontalFrame2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.horizontalFrame2.setMidLineWidth(2)
        self.horizontalFrame2.setObjectName("horizontalFrame2")
        self.pushButton = QtWidgets.QPushButton(self.horizontalFrame2)
        self.pushButton.setGeometry(QtCore.QRect(10, 0, 31, 31))
        self.pushButton.setMaximumSize(QtCore.QSize(332, 16777215))
        self.pushButton.setStyleSheet("image: url(:/image/file.png);\n"
"background-image: url(:/image/file.png);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalFrame2)
        self.pushButton_5.setGeometry(QtCore.QRect(60, 0, 31, 31))
        self.pushButton_5.setStyleSheet("background-image: url(:/image/network.png);")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.horizontalFrame2)
        self.pushButton_6.setGeometry(QtCore.QRect(100, 0, 31, 31))
        self.pushButton_6.setStyleSheet("background-image: url(:/image/capture.png);")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_11 = QtWidgets.QPushButton(self.horizontalFrame2)
        self.pushButton_11.setGeometry(QtCore.QRect(140, -10, 71, 61))
        self.pushButton_11.setStyleSheet("background-image: url(:/image/style1.png);")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.horizontalFrame2)
        self.pushButton_12.setGeometry(QtCore.QRect(360, 50, 41, 34))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_17 = QtWidgets.QPushButton(self.horizontalFrame2)
        self.pushButton_17.setGeometry(QtCore.QRect(210, -10, 71, 61))
        self.pushButton_17.setStyleSheet("background-image: url(:/image/style2.png);")
        self.pushButton_17.setText("")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.horizontalFrame2)
        self.pushButton_18.setGeometry(QtCore.QRect(290, -10, 71, 61))
        self.pushButton_18.setStyleSheet("background-image: url(:/image/style4.png);")
        self.pushButton_18.setText("")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.horizontalFrame2)
        self.pushButton_19.setGeometry(QtCore.QRect(360, -10, 71, 61))
        self.pushButton_19.setStyleSheet("\n"
"background-image: url(:/image/style16.png);")
        self.pushButton_19.setText("")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_12.raise_()
        self.pushButton_11.raise_()
        self.pushButton_17.raise_()
        self.pushButton_18.raise_()
        self.pushButton_19.raise_()
        self.gridLayout.addWidget(self.horizontalFrame2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 699, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuopen = QtWidgets.QMenu(self.menu)
        self.menuopen.setObjectName("menuopen")
        self.menu_V = QtWidgets.QMenu(self.menubar)
        self.menu_V.setObjectName("menu_V")
        self.menu_H = QtWidgets.QMenu(self.menubar)
        self.menu_H.setObjectName("menu_H")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCtrl_F = QtWidgets.QAction(MainWindow)
        self.actionCtrl_F.setObjectName("actionCtrl_F")
        self.action_Crtl_N = QtWidgets.QAction(MainWindow)
        self.action_Crtl_N.setObjectName("action_Crtl_N")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.menuopen.addAction(self.actionCtrl_F)
        self.menu.addAction(self.menuopen.menuAction())
        self.menu.addAction(self.action_Crtl_N)
        self.menu.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_V.menuAction())
        self.menubar.addAction(self.menu_H.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "camera"))
        self.pushButton_12.setText(_translate("MainWindow", "PushButton"))
        self.menu.setTitle(_translate("MainWindow", "媒体（M）"))
        self.menuopen.setTitle(_translate("MainWindow", "打开文件源               Crtl+F"))
        self.menu_V.setTitle(_translate("MainWindow", "视图（V）"))
        self.menu_H.setTitle(_translate("MainWindow", "帮助（H）"))
        self.actionCtrl_F.setText(_translate("MainWindow", "Ctrl+F"))
        self.action_Crtl_N.setText(_translate("MainWindow", "打开网络源               Crtl+N"))
        self.action_2.setText(_translate("MainWindow", "打开捕获设备            Crtl+C"))
# import image_rc
# import skin_rc

# import img_rc

# 主方法
if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow() # 创建窗体对象
    ui = Ui_MainWindow() # 创建PyQt5设计的窗体对象
    ui.setupUi(MainWindow) # 调用PyQt5窗体的方法对窗体对象进行初始化设置
    MainWindow.show() # 显示窗体
    sys.exit(app.exec_()) # 程序关闭时退出进程